[:div#panel-1
	[:img.action-1-6 {:src "./images/1-6.png"}]
	[:img.action-1-5 {:src "./images/1-5.png"}]
	[:img.action-1-4 {:src "./images/1-4.png"}]
	[:img.action-1-3 {:src "./images/1-3.png"}]
	[:img.action-1-2 {:src "./images/1-2.png"}]
	[:img {:src "./images/1-1.png"}]
]
[:div#panel-2
	[:img.action-2-5 {:src "./images/2-5.png"}]
	[:img.action-2-4 {:src "./images/2-4.png"}]
	[:img.action-2-3 {:src "./images/2-3.png"}]
	[:img.action-2-2 {:src "./images/2-2.png"}]
	[:img {:src "./images/2-1.png"}]
]
[:div#panel-3
	[:img.action-3-5 {:src "./images/3-5.png"}]
	[:div.action-3-4-1 [:img.action-3-4-2 {:src "./images/3-4.png"}]]
	[:img.action-3-3 {:src "./images/3-3.png"}]
	[:img.action-3-2 {:src "./images/3-2.png"}]
	[:img {:src "./images/3-1.png"}]
]
[:div#panel-4
	[:img.action-4-5 {:src "./images/4-5.png"}]
	[:img.action-4-4 {:src "./images/4-4.png"}]
	[:img.action-4-3 {:src "./images/4-3.png"}]
	[:img.action-4-2 {:src "./images/4-2.png"}]
	[:img {:src "./images/4-1.png"}]
]
[:div#panel-5
	[:img.action-5-6 {:src "./images/5-6.png"}]
	[:img.action-5-5 {:src "./images/5-5.png"}]
	[:img.action-5-4 {:src "./images/5-4.png"}]
	[:img.action-5-3 {:src "./images/5-3.png"}]
	[:img.action-5-2 {:src "./images/5-2.png"}]
	[:img {:src "./images/5-1.png"}]
]
